### ISSUE TITLE
ChanTimeFreq time axis

### ISSUE THREAD

**Issue by bdyetton** [wonambi-python/wonambi#14]
Hi Wonambi Team,
I'm using time-frequency to extract a spectrogram which i will use to calculate band power.
The ChanTimeFreq data returned from timefrequency has an axis attribute. I see that for frequency this is something like [0, 1, 2, ...] this makes me think these are the edges of the freq bins, and not the centers, is that right? So the first freq sample is 0-1Hz, the next 1-2Hz, etc. If so, then is the last value (say X) everything above that X, or X + freq_bin_size (1 Hz in this case). 
Further, for time, the bins are like [4, 8, 12, 16, etc] which seem like edges (but the upper edge, not the lower edge as for freq). Does this mean the first time sample is from 0-4s, the next from 8-12s, or are these centers, where the first bin is 2-6s, then 6-10s, etc, and the first 2 seconds is lost (due to scipy's spectrogram function).
If you could clear up this ambiguity, that would be amazing :)

**Comment by gpiantoni** [comment]
I'm pretty sure that the values for both frequency and time axes are the centers. So, in the case of frequencies, 0Hz is the DC offset. The last value should be nyquist frequency - 1. I think. 

I need to check the time bins. Any chance you could share the code you use exactly?

Thanks

**Comment by bdyetton** [comment]
Ah, that makes sense, so the first bin is DC power, and then each extra bin is the center freq.
That leads me to believe that the time would centers too, and because scipy's spectrogram cannot calculate the first X seconds (can't remember why, something to do with fft), then the first time sample will be offset a little.

The code i used is pretty simple, and almost the exact example you guys have in the docs:
```python
    d = Dataset(edf_filepath)
    data = d.read_data(begtime=start_time, endtime=end_time, chan=chans_to_consider)
    power = timefrequency(data, method='spectrogram')
    abs_power = math(power, operator_name='abs')
    time_axis = np.round(abs_power.axis['time'][0], 2)
    freq_axis = np.round(abs_power.axis['freq'][0], 2)
```

**Comment by bdyetton** [comment]
Hi Guys,
Just following up on the timing axis units. It's correct they are centers? or left or right edges?
Thanks :)

**Comment by jnobyrne** [comment]
Hi Benjamin,

I just had a look, and you're correct that for both the time and frequency axes output from timefrequency, the bin values represent the bin centres.

Best,
Jordan

**Comment by bdyetton** [comment]
Awesome, thanks!
