### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by bdyetton** [wonambi-python/wonambi#17]
Hi Wonambi Team,
When running:
```python
    d = Dataset('example1_sleep_rec.edf')
    data = d.read_data(chan=['C3-A2'])
    power = timefrequency(data, method='spectrogram')
```
I get:
```Process finished with exit code -1073741819 (0xC0000005)```

[example1_sleep_rec.zip](https://github.com/wonambi-python/wonambi/files/3114482/example1_sleep_rec.zip)

**Comment by bdyetton** [comment]
This does not happen when 2 channels are included:
[example1_sleep_rec.zip](https://github.com/wonambi-python/wonambi/files/3114490/example1_sleep_rec.zip)
where: ```d.read_data(chan=['C3-A2'])``` --> ```d.read_data(chan=['C3-A2','C4-A1'])```

**Comment by gpiantoni** [comment]
Thanks a lot for the example code and data. Unfortunately I was not able to replicate this issue. I tested with python 3.7 on Linux and with a fresh anaconda install (Python 3.7) on Windows. Googling the error that you reported seems to indicate that it's an issue with the python installation (maybe some numpy or Qt library issue). It doesn't look like a normal python error.

Could you try to see if you see the same issue with a fresh installation of miniconda, for example? Thisis what I did on Windows. After downloading and installing the miniconda package at https://docs.conda.io/en/latest/miniconda.html for python 3.7, I simply did:

    conda install -y numpy scipy 
    pip install wonambi

and then I ran the code you sent me.

Thanks

**Comment by bdyetton** [comment]
Your right! My bad. I should have replicated on another machine.
Closing!
btw, would you be interested in a combined effort to validate the spindle detectors?
We have some high quality spindle data here: https://osf.io/8bma7/wiki/home/

**Comment by gpiantoni** [comment]
Thanks for the report! Actually I'm not working on spindles at the moment but @jnobyrne will probably be interested.
