### ISSUE TITLE
Unit Convertion

### ISSUE THREAD

**Issue by bdyetton** [wonambi-python/wonambi#20]
Hi Wonambi Team,
Does Wonambi convert units to something standard, or have functions for doing that? I didnt see any in the docs..
For example, i have files with mixed units (some in uV and some in mV) and im wondering if they get standardized automatically, or that's something I should do?
Also, are the detectors build to work on uV, mV or V?

**Comment by jnobyrne** [comment]
Hi Benjamin,

I'm not so familiar with other data formats, but for EDF, Wonambi assumes all values are in microvolts (uV). My guess is it's the same for all classes. What data format are you using?

The spindle and slow wave detectors are designed to work on microvolt (uV) signal.

Best,
Jordan

**Comment by bdyetton** [comment]
Excellent thanks, I'm using EDFs. Most are in uV and some in mV, so i'll convert those.
Probably best to make a note that wonambi assumes uV somewhere in the docs.
