### ISSUE TITLE
Documentation on use with Python.

### ISSUE THREAD

**Issue by biggzlar** [wonambi-python/wonambi#24]
Hey there,

I'd like to use wonambi to load some lfp recordings for further processing in Python. Unfortunately, I wasn't able to find anything on using this package without the GUI in the docs. Could anyone give me a minimal example of how to read in a '.ns3' file?

If there is any documentation on this, then it should probably be a bit more prominent. If there isn't, then it should definitely be added to the docs.

Thanks in advance.

**Comment by gpiantoni** [comment]
Fair comment. Sorry about the lack of the documentation and thanks for your interest. Here are some pointers:

    from wonambi import Dataset
    d = Dataset('/path/to/blackrock.ns3')
    markers = d.read_markers()  # it reads the nev file if present
    data = d.read_data(begtime=10, endtime=30)
    freq = frequency(data, scaling='power')

I'll leave this issue open to remind myself to write a "get-started" tutorial.

**Comment by biggzlar** [comment]
Excellent. Thank you for the fast response.

**Comment by gpiantoni** [comment]
I added this simple page: https://wonambi-python.github.io/analysis/tutorial.html
Sorry if it's so short. I'll close this issue. I'll try to add more content in the future.
