### ISSUE TITLE
An import breaks down with newest scipy versions

### ISSUE THREAD

**Issue by arnoudvanderleer** [wonambi-python/wonambi#37]
On December 11, 2023, a change was made in scipy that (as far as I understand it) removes the already deprecated import redirect of `tukey` from `scipy.signal` to `scipy.signal.windows` ([see the diff](https://github.com/scipy/scipy/commit/bf9c8dfd59eec07c666beefc45c02ea1ba6afe7c#diff-8a86dc2a183f9ba07ca885153ab1309491e6c0d0e8d5977a0006753eeb7869fe)). This means that the import of `tukey` in `C:\[...]\site-packages\wonambi\detect\spindle.py` breaks down with the newest versions of scipy (>= 12.0.1).

**Comment by gpiantoni** [comment]
thank you for the clear error message. The error should be fixed now, with commit https://github.com/wonambi-python/wonambi/commit/530a52eaa901efa47bc665f932a0cdd92a97d85b

The working version has been released to pypi (version v7.13).

Please reopen the issue if it hasn't been solved

**Comment by arnoudvanderleer** [comment]
Thanks for fixing ths!
