### ISSUE TITLE
spindle detection example

### ISSUE THREAD

**Issue by Slasnista** [wonambi-python/wonambi#5]
Hi,

First of all I would like to thank you for providing such a library which was exactly what I was looking for !

I am a PhD student under A. Gramfort's supervision and I am currently working on spindle detection. I would like to use the methods you have implemented in my benchmark. Would you have a running example / notebook to illustrate how to perform spindle detection with wonambi from the edf extraction up to the detection ?

Furthermore, how should I cite this library ?

Thanks in advance,
Stanislas Chambon

**Comment by gpiantoni** [comment]
Thanks for your interest! 
If you want to use the GUI, you can follow the instructions [here](https://wonambi-python.github.io/gui/open.html) and [here](https://wonambi-python.github.io/gui/detect.html). 
We don't have a tutorial but there is quite some documentation [here](https://wonambi-python.github.io/gui/index.html).

If you want to use the commands, you could do something like:
```
from wonambi import Dataset
d = Dataset('path_to_edf.edf')
data = d.read_data(begtime=10, endtime=100)
from wonambi.detect import DetectSpindle
detection = DetectSpindle('Ferrarelli2007')
spindles = detection(data)
```
Please, let me or @jburn know if you bump into any issue. Happy to help

**Comment by Slasnista** [comment]
Great, it works perfectly well ! Thanks a lot for the support !
